#!/usr/bin/env python3

from sys import argv as a

progname = a[0].split('/')[-1]

def print_usage():
    print(f'{progname} [options] [fileprefix ...]')
    exit(1)

if len(a) == 1:
    print_usage()

fileprefixes = []
react = ''

for arg in a[1:]:
    if arg[0] == '-':
        if arg in ['-r', '--react']:
            react = '<react></react>'
        else:
            print(f'Unknown option {arg}')
            print_usage()
    else:
        fileprefixes.append(arg)

html=f'''\
<!DOCTYPE html>
<html>
<head>
</head>
<body>
{react}
</body>
</html>
'''

for fileprefix in fileprefixes:
    open(fileprefix + '.html', 'w').write(html)
